environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python34-x64"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
install:
    - "%PYTHON%\\python.exe -m pip install -U pytest-flake8 pytest-pylint pytest-cov codecov"
build: off
test_script:
    - "%PYTHON%\\python.exe -m pytest -v --cache-clear --flake8 --pylint --cov=. --cov-report term-missing"
on_success:
    - "%PYTHON%\\python.exe -m codecov"
